### ISSUE TITLE
Customers data fields are not visible

### ISSUE THREAD

**Issue by tomasced** [anoblet/aybolit#21]
Not all fields are visible. Need to fix opacity level for below fields:

![image](https://user-images.githubusercontent.com/53396400/134395843-ea446984-0b0f-4a66-a7ad-b43a504bc946.png)

**Comment by anoblet** [comment]
Fixed

https://github.com/anoblet/aybolit/blob/8566ba9e37c210fa27d4e9b21e8355fd3cb59f6a/packages/cxl-ui/src/components/cxl-dashboard/BaseElements/BaseElement.js#L10
